#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t "jalgoarena/problems-store:1.0.$TRAVIS_BUILD_NUMBER" .
docker push "jalgoarena/problems-store:1.0.$TRAVIS_BUILD_NUMBER"