[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.13.5"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"
