[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.13.5"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mitchellh/gox"
  version = "0.4.0"
